# Generated by Django 3.0.6 on 2020-05-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('lawyer_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('mid_name', models.CharField(max_length=25)),
                ('specialization', models.CharField(max_length=20)),
                ('mail_info', models.EmailField(max_length=30)),
            ],
        ),
    ]
