# Generated by Django 3.0.6 on 2020-05-07 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
