# Generated by Django 3.0.6 on 2020-05-05 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_juridical',
            fields=[
                ('first_name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('mid_name', models.CharField(max_length=25)),
                ('adr_city', models.CharField(max_length=30)),
                ('adr_street', models.TextField()),
                ('adr_build', models.IntegerField()),
                ('mail_info', models.EmailField(max_length=30)),
                ('num_client_j', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('clint_position', models.CharField(max_length=25)),
                ('name_of_company', models.CharField(max_length=25)),
                ('iban', models.CharField(max_length=29)),
            ],
            options={
                'db_table': 'Client_juridical',
                'ordering': ['first_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client_natural',
            fields=[
                ('first_name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('mid_name', models.CharField(max_length=25)),
                ('adr_city', models.CharField(max_length=30)),
                ('adr_street', models.TextField()),
                ('adr_build', models.IntegerField()),
                ('mail_info', models.EmailField(max_length=30)),
                ('num_client_n', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('birth_date', models.DateField()),
                ('passport_date', models.DateField()),
                ('passport_authority', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'Client_natural',
                'ordering': ['first_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Phone',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name_service', models.CharField(max_length=50)),
                ('nominal_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bonus_value', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Work_days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3)),
            ],
            options={
                'db_table': 'Work_days',
            },
        ),
        migrations.AlterModelOptions(
            name='lawyer',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterModelTable(
            name='lawyer',
            table='Lawyer',
        ),
        migrations.CreateModel(
            name='Dossier_N',
            fields=[
                ('issue', models.TextField()),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('closed-won', 'closed-won')], default='open', max_length=10)),
                ('date_signed', models.DateField()),
                ('date_expired', models.DateField()),
                ('date_closed', models.DateField(blank=True)),
                ('paid', models.BooleanField(default=False)),
                ('court_name', models.CharField(blank=True, max_length=50)),
                ('court_adr', models.CharField(blank=True, max_length=50)),
                ('court_date', models.DateTimeField(null=True)),
                ('code_dossier_n', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('lawyer_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DataBase.Lawyer')),
                ('num_client_n', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DataBase.Client_natural')),
            ],
            options={
                'db_table': 'Dossier_N',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dossier_J',
            fields=[
                ('issue', models.TextField()),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('closed-won', 'closed-won')], default='open', max_length=10)),
                ('date_signed', models.DateField()),
                ('date_expired', models.DateField()),
                ('date_closed', models.DateField(blank=True)),
                ('paid', models.BooleanField(default=False)),
                ('court_name', models.CharField(blank=True, max_length=50)),
                ('court_adr', models.CharField(blank=True, max_length=50)),
                ('court_date', models.DateTimeField(null=True)),
                ('code_dossier_j', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('lawyer_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DataBase.Lawyer')),
                ('num_client_j', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DataBase.Client_juridical')),
            ],
            options={
                'db_table': 'Dossier_J',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client_natural',
            name='phone_num',
            field=models.ManyToManyField(to='DataBase.Phone'),
        ),
        migrations.AddField(
            model_name='client_juridical',
            name='phone_num',
            field=models.ManyToManyField(to='DataBase.Phone'),
        ),
        migrations.CreateModel(
            name='Appointment_N',
            fields=[
                ('app_date', models.DateField()),
                ('app_time', models.TimeField()),
                ('comment', models.TextField()),
                ('appoint_code_n', models.AutoField(primary_key=True, serialize=False)),
                ('code_dossier_n', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DataBase.Dossier_N')),
                ('lawyer_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DataBase.Lawyer')),
                ('num_client_n', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DataBase.Client_natural')),
                ('phone_num', models.ManyToManyField(to='DataBase.Phone')),
                ('service', models.ManyToManyField(to='DataBase.Services')),
            ],
            options={
                'db_table': 'Appointment_N',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment_J',
            fields=[
                ('app_date', models.DateField()),
                ('app_time', models.TimeField()),
                ('comment', models.TextField()),
                ('appoint_code_j', models.AutoField(primary_key=True, serialize=False)),
                ('code_dossier_j', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DataBase.Dossier_J')),
                ('lawyer_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DataBase.Lawyer')),
                ('num_client_j', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DataBase.Client_juridical')),
                ('phone_num', models.ManyToManyField(to='DataBase.Phone')),
                ('service', models.ManyToManyField(to='DataBase.Services')),
            ],
            options={
                'db_table': 'Appointment_J',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lawyer',
            name='phone_num',
            field=models.ManyToManyField(to='DataBase.Phone'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='service',
            field=models.ManyToManyField(to='DataBase.Services'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='work_days',
            field=models.ManyToManyField(to='DataBase.Work_days'),
        ),
    ]
