# Generated by Django 3.0.6 on 2020-05-07 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0002_delete_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_juridical',
            old_name='clint_position',
            new_name='client_position',
        ),
        migrations.RemoveField(
            model_name='jphone',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lphone',
            name='id',
        ),
        migrations.RemoveField(
            model_name='nphone',
            name='id',
        ),
        migrations.AlterField(
            model_name='appointment_j',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment_n',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dossier_j',
            name='court_adr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dossier_j',
            name='court_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dossier_j',
            name='court_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dossier_j',
            name='lawyer_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DataBase.Lawyer'),
        ),
        migrations.AlterField(
            model_name='dossier_n',
            name='court_adr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dossier_n',
            name='court_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dossier_n',
            name='court_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dossier_n',
            name='lawyer_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DataBase.Lawyer'),
        ),
        migrations.AlterField(
            model_name='jphone',
            name='phone_num',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lphone',
            name='phone_num',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nphone',
            name='phone_num',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
