# Generated by Django 3.0.6 on 2020-05-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0003_auto_20200507_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier_j',
            name='date_closed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dossier_n',
            name='date_closed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
