# Generated by Django 3.0.6 on 2020-05-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0004_auto_20200507_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_juridical',
            name='num_client_j',
            field=models.CharField(help_text='EDRPOU code', max_length=8, primary_key=True, serialize=False),
        ),
    ]
