from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/<pk>/<mail>/', views.register, name='register'),
    path('statistics/', views.StatisticsView.as_view(), name='stats'),
    path('lawyers/', views.LawyerListView.as_view(), name='lawyers'),
    path('services/', views.ServicesListView.as_view(), name='services'),
    path('jcustomers/', views.Client_juridicalListView.as_view(), name='jcustomers'),
    path('ncustomers/', views.Client_naturalListView.as_view(), name='ncustomers'),
    path('ndossiers/', views.Dossier_NListView.as_view(), name='ndossiers'),
    path('jdossiers/', views.Dossier_JListView.as_view(), name='jdossiers'),
    path('nappointments/', views.Appointment_NListView.as_view(), name='nappointments'),
    path('jappointments/', views.Appointment_JListView.as_view(), name='jappointments'),
    path('lawyer/<pk>/', views.LawyerDetailView.as_view(), name='lawyer-detailed-view'),
    path('lawyer/create', views.LawyerCreateView.as_view(), name='lawyer-create'),
    path('lawyer/<pk>/update', views.LawyerUpdateView.as_view(), name='lawyer-update'),
    path('lawyer/<pk>/delete', views.lawyerDelete, name='lawyer-delete'),
    path('client_N/create', views.Client_naturalCreateView.as_view(), name='client_natural-create'),
    path('client_N/<pk>/update', views.Client_naturalUpdateView.as_view(), name='client_natural-update'),
    path('client_N/<pk>/delete', views.nclientDelete, name='client_natural-delete'),
    path('client_J/create', views.Client_juridicalCreateView.as_view(), name='client_juridical-create'),
    path('client_J/<pk>/update', views.Client_juridicalUpdateView.as_view(), name='client_juridical-update'),
    path('client_J/<pk>/delete', views.jclientDelete, name='client_juridical-delete'),
    path('appointment_N/create', views.Appointment_NCreateView.as_view(), name='appointment_n-create'),
    path('appointment_J/create', views.Appointment_JCreateView.as_view(), name='appointment_j-create'),
    path('appointment_N/<pk>/update', views.Appointment_NUpdateView.as_view(), name='appointment_n-update'),
    path('appointment_J/<pk>/update', views.Appointment_JUpdateView.as_view(), name='appointment_j-update'),
    path('appointment_N/<pk>/delete', views.nappointDelete, name='appointment_n-delete'),
    path('appointment_J/<pk>/delete', views.jappointDelete, name='appointment_j-delete'),
    path('service_group/create', views.ServiceGroupCreateView.as_view(), name='service_group-create'),
    path('service/create', views.ServicesCreateView.as_view(), name='service-create'),
    path('service/<pk>/update', views.ServicesUpdateView.as_view(), name='service-update'),
    path('service/<pk>/delete', views.serviceDelete, name='service-delete'),
    path('dossier_N/<pk>/create', views.Dossier_NCreateView.as_view(), name='dossier_n-create'),
    path('dossier_J/<pk>/create', views.Dossier_JCreateView.as_view(), name='dossier_j-create'),
    path('dossier_N/<pk>/update', views.Dossier_NUpdateView.as_view(), name='dossier_n-update'),
    path('dossier_N/<pk>/delete', views.ndossierDelete, name='dossier_n-delete'),
    path('dossier_J/<pk>/update', views.Dossier_JUpdateView.as_view(), name='dossier_j-update'),
    path('dossier_J/<pk>/delete', views.jdossierDelete, name='dossier_j-delete'),
    path('service/<pk>/', views.ServiceDetailView.as_view(), name='service-detailed-view'),
    path('client_N/<pk>/', views.ClientNDetailView.as_view(), name='client-detailed-view-n'),
    path('client_J/<pk>/', views.ClientJDetailView.as_view(), name='client-detailed-view-j'),
    path('dossier_N/<pk>/', views.DossierDetailNView.as_view(), name='dossier-detailed-n'),
    path('dossier_J/<pk>/', views.DossierDetailJView.as_view(), name='dossier-detailed-j'),
    path('getstats/', views.getStats, name='get-stats'),
    path('sendServices/', views.service_ajax, name='get-lawyer'),
    path('sendClient/', views.client_ajax, name='get-dossier'),
    path('lawyerWorkDays/', views.lawyer_work_days, name='get-workdays'),
    path('dayBlockedTime/', views.dayblockedtime, name='get-blockedtime'),
    path('lawyerServiceCode/',views.lawyer_service_code, name='get-service-lawyers'),
    path('service/<pk>/addLawyer', views.LawyerServiceCreateView.as_view(), name='add-service-lawyer'),
]
